#!/usr/bin/env node

/**
 * Socket.IO context
 * 
 * @author Vladimir Dronnikov <dronnikov@gmail.com>
 * @license The MIT license.
 * @copyright Copyright (c) 2011 Vladimir Dronnikov <dronnikov@gmail.com>
 */

/*
 * This file will help you bundle socket.io.js and context.js
 * You can later use Google Closure Compiler on it.
 */

var fs = require('fs'),
	io = require('socket.io-client/lib/io'),
	jsp = require('socket.io-client/lib/vendor/uglifyjs/lib/parse-js'),
	pro = require("socket.io-client/lib/vendor/uglifyjs/lib/process"),
	ast,
	files = [
		__dirname + '/example/es5-shim.js',
		require('socket.io-client').dist + '/socket.io.js',
		__dirname + '/context.js',
	],
	content = "/** Socket.IO "+ io.version +" - Built with build.js */\n",
	license = "/* Socket.IO.min "+ io.version +" @author Guillermo Rauch <guillermo@learnboost.com>, @license The MIT license., @copyright Copyright (c) 2010 LearnBoost <dev@learnboost.com> */\n";

console.log('Reading files…');

files.forEach(function(path){
	console.log(' + ' + path);
	content += fs.readFileSync(path) + "\n";
});

console.log('Generating…');

fs.write(fs.openSync(__dirname + '/context0.js', 'w'), content, 0, 'utf8');
console.log(' + ' + __dirname + '/context0.js');

console.log('Uglyfying…');
ast = jsp.parse(content);
ast = pro.ast_mangle(ast); // get a new AST with mangled names
ast = pro.ast_squeeze(ast);
fs.write(fs.openSync(__dirname + '/context.min.js', 'w'), license + pro.gen_code(ast), 0, 'utf8');
console.log(' + ' + __dirname + '/context.min.js');

console.log('All done!');
